### ISSUE TITLE
Apply a filter in the species remaining in the outputs of GTA. 

### ISSUE THREAD

**Issue by BastienIRD** [firms-gta/geoflow-tunaatlas#10]
For now, all the species provided by tRFMOs remain in the output of level 0. A species list https://github.com/fdiwg/fdi-codelists is available for level 0 Global Tuna Atlas and should be integrated in the workflow.

**Comment by eblondel** [comment]
We don't need to integrate it in the workflow, and in general we should avoid to load codelists in the DB if they are not strictly needed there. You can query directly the codelist from fdi-codelists repository (that's why it was created). In that case you can read it directly through `readr`. You can then do the same for the level 1 where i've added the list of 8 species mentioned  by @manuchassot

**Comment by eblondel** [comment]
Generally speaking, we tend progressively to remove codelists and mappings resources at the beginning of the workflow, when they are not needed. The strategy that binds the workflow to the DB resources make the workflow heavier and more difficult to maintain, and we have been tending to remove this dependency; first we did it by using the Google Drive as middle storage, and now we do it with the Github fdiwg / CWP repositories.

**Comment by eblondel** [comment]
@BastienIRD , please don't use GTA_SPECIES_LIST_DRAFT.csv but the standardized one `cl_species_level0`
For level 1, i've added `cl_species_level1`
Thanks in advance
